/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/auth': RouteRecordInfo<'/auth', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/register': RouteRecordInfo<'/auth/register', '/auth/register', Record<never, never>, Record<never, never>>,
    '/authority-manage': RouteRecordInfo<'/authority-manage', '/authority-manage', Record<never, never>, Record<never, never>>,
    '/authority-manage/permission': RouteRecordInfo<'/authority-manage/permission', '/authority-manage/permission', Record<never, never>, Record<never, never>>,
    '/authority-manage/roles': RouteRecordInfo<'/authority-manage/roles', '/authority-manage/roles', Record<never, never>, Record<never, never>>,
    '/authority-manage/user-role': RouteRecordInfo<'/authority-manage/user-role', '/authority-manage/user-role', Record<never, never>, Record<never, never>>,
    '/data-manage': RouteRecordInfo<'/data-manage', '/data-manage', Record<never, never>, Record<never, never>>,
    '/data-manage/dict': RouteRecordInfo<'/data-manage/dict', '/data-manage/dict', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/setting': RouteRecordInfo<'/setting', '/setting', Record<never, never>, Record<never, never>>,
  }
}
